# Generated by Django 4.2.13 on 2024-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Sản phẩm"},
        ),
        migrations.AlterModelOptions(
            name="productdetail",
            options={},
        ),
    ]
