# Generated by Django 4.2.11 on 2024-04-12 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productdetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categgory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="categgory_name",
            new_name="category_name",
        ),
    ]
