# Generated by Django 4.2.11 on 2024-04-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_categgory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name_plural': 'ProductDetails'},
        ),
    ]
