# Generated by Django 4.2.11 on 2024-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="product.category"),
        ),
    ]
