# Generated by Django 4.2.11 on 2024-04-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name_plural': 'Cart Details'},
        ),
        migrations.AlterUniqueTogether(
            name='cartdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
