# Generated by Django 4.2.11 on 2024-04-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
