# Generated by Django 4.2.13 on 2024-05-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
